CREATE TABLE tracks (
    id        INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title     TEXT NOT NULL CHECK (title <> ''),
    singer    TEXT NOT NULL CHECK (singer <> ''),
    album     TEXT NOT NULL CHECK (album <> ''),
    duration  TEXT NOT NULL CHECK (duration <> '')
);